### ISSUE TITLE
can't get session

### ISSUE THREAD

**Issue by usama7628674** [AbedAlqaderSwedan1/ASWCrypter#1]
@AbedAlqaderSwedan1 Upon runnning .hta file in windows 10 v1803 I got no session back to meterpreter shell.Any idea why?

**Comment by AbedAlqaderSwedan1** [comment]
Tested on  Windows 10 v1511 I got a session, are you sure for your setting?

**Comment by usama7628674** [comment]
@AbedAlqaderSwedan1 Yes I am dead sure.I tried with reverse_tcp & reverse_http and no session at the end.Windows firewall was off and defender didn't flag anything.I'll try on my VM win 10 v1709 tomorrow and see if I could get a session.

Metasploit version 4.17.7
OS kali linux 2018.3

**Comment by AbedAlqaderSwedan1** [comment]
Ok my friend please keep me updated

**Comment by usama7628674** [comment]
@AbedAlqaderSwedan1 Updated to version 1.2 but still not working on windows 10 v1709.

**Comment by usama7628674** [comment]
@AbedAlqaderSwedan1 Windows defender detected it silently without any notification.The following is proof
**Tested on windows 10 v1803**

![capture11111](https://user-images.githubusercontent.com/29252277/44625484-72847400-a924-11e8-9cdc-cb28fa275782.PNG)

**Comment by AbedAlqaderSwedan1** [comment]
#Backdoor Tested On WinXP, Win7, Win8 All version, Win10(1151) 

Last version for win 10 until this time it can't bypass it I will upload a new update after 2day
