### ISSUE TITLE
It can't bypass antivirus of windows 10

### ISSUE THREAD

**Issue by hieutrandn9889** [AbedAlqaderSwedan1/ASWCrypter#2]
Hello,

It can't bypass antivirus of windows 10

How to update latest version ?

**Comment by usama7628674** [comment]
@hieutrandn9889 See #1

**Comment by AbedAlqaderSwedan1** [comment]
#Backdoor Tested On WinXP, Win7, Win8 All version, Win10(1151) 

Last version for win 10 until this time it can't bypass it I will upload a new update after 2day
